// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-7jVsNb_qXgoNyrRnjDKZRpPA6W_n4GU',
    appId: '1:152922673520:android:e989793a923b5b2b5b7fb5',
    messagingSenderId: '152922673520',
    projectId: 'socialconnect-29ea0',
    storageBucket: 'socialconnect-29ea0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAObLn6etpLGrOt7_luLAcrcJdjjpcqAQk',
    appId: '1:921305845988:ios:7bfcda3445e0a3db005cf1',
    messagingSenderId: '921305845988',
    projectId: 'regal-campus-232410',
    storageBucket: 'regal-campus-232410.firebasestorage.app',
    databaseURL: 'https://regal-campus-232410.firebaseio.com',
    iosClientId:
        '921305845988-u6gvsr7pag5utvnks8rsefpil1oh0m6d.apps.googleusercontent.com',
    iosBundleId: 'social.dineshkokare.connect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAObLn6etpLGrOt7_luLAcrcJdjjpcqAQk',
    appId: '1:921305845988:ios:7bfcda3445e0a3db005cf1',
    messagingSenderId: '921305845988',
    projectId: 'regal-campus-232410',
    storageBucket: 'regal-campus-232410.firebasestorage.app',
    databaseURL: 'https://regal-campus-232410.firebaseio.com',
    iosClientId:
        '921305845988-u6gvsr7pag5utvnks8rsefpil1oh0m6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialconnect.socialConnect',
  );
}
